app/models/result.py
from app.extensions import db
from datetime import datetime

class Result(db.Model):
    id = db.Column(db.Integer, primary_key = True) # Primary key for the result
    input_filename = db.Column(db.String(64), index = True, unique = True) # Filename of the result
    result_filename = db.Column(db.String(64), index = True, unique = True) # Filename of the result
    result_html = db.Column(db.String(64), index = True, unique = True) # Hyperlink to the result
    timestamp = db.Column(db.DateTime, index = True, default = datetime.utcnow) # Timestamp of the result

    def __repr__(self):
        return "<Result {}>".format(self.result)

app/__init__.py
from flask import Flask

from config import Config
from app.extensions import db

def create_app(config_class = Config):
    app = Flask(__name__)
    app.config.from_object(config_class)
   
    # Initialize any extensions here
    db.init_app(app)

    # Register blueprints here
    from app.home import bp as home_bp
    app.register_blueprint(home_bp, url_prefix = "/") # Register the home blueprint with the app, with the url prefix "/"

    from app.experiment import bp as experiment_bp
    app.register_blueprint(experiment_bp, url_prefix = "/experiment") # Register the experiment blueprint with the app, with the url prefix "/experiment"

    from app.results import bp as results_bp
    app.register_blueprint(results_bp, url_prefix = "/results") # Register the results blueprint with the app, with the url prefix "/results"

    from app.acknowledgements import bp as acknowledgements_bp
    app.register_blueprint(acknowledgements_bp, url_prefix = "/acknowledgements") # Register the results blueprint with the app, with the url prefix "/acknowledgements"

    '''
    url_prefix is mainly used for jinja2 url_for() function, 
    which generates a URL to the given endpoint with the method provided.
    
    For example, url_for("results.index") will return "/results/" instead of 
    "/".
    '''

    return app

app/acknowledgements/__init__.py
from flask import Blueprint # Import flask Blueprint class for the blueprint object

bp = Blueprint("acknowledgements", __name__) # Create a blueprint object for the experiment blueprint, with the name "experiment"

from app.acknowledgements import routes # Import the routes module from the experiment package

app/acknowledgements/routes.py
from flask import render_template, redirect, url_for
from app.acknowledgements import bp

@bp.route("/") # Decorator for the index function, which is the view function for the index page
def index(): # View function for the index page
    return render_template("acknowledgements/acknowledgements.html")

app/experiment/__init__.py
from flask import Blueprint # Import flask Blueprint class for the blueprint object

bp = Blueprint("experiment", __name__) # Create a blueprint object for the experiment blueprint, with the name "experiment"

from app.experiment import routes # Import the routes module from the experiment package

app/experiment/routes.py
import os
from flask import current_app, render_template, redirect, request, session, url_for
from werkzeug.utils import secure_filename
from app.experiment import bp
import pandas as pd
import hpo.src.main as hpo

@bp.route("/", methods=["GET", "POST"]) # Decorator for the index function, which is the view function for the index page
def index(): # View function for the index page
    if request.method == "POST":
        # session["experiment_metadata"] = request.form
        return redirect(url_for("experiment.upload_dataset"))
    return render_template("experiment/new_experiment.html") # Render the experiment template (experiment.html), which will fill any jinja2 template tags with the values provided in the render_template function call




@bp.route("/upload_dataset", methods=["GET", "POST"])
def upload_dataset():
    if request.method == "POST":
        file = request.files["dataset"]
        file_name = secure_filename(file.filename)
        file.save(os.path.join(current_app.config["UPLOAD_FOLDER"], file_name))
        hpo.Main.main()
        return redirect(url_for("results.index", filename=file_name))
    return render_template("experiment/upload_dataset.html")

# @bp.route("/configure_dataset/<file_name>")
# def configure_dataset(file_name):
#     df = pd.read_csv(os.path.join(current_app.config["UPLOAD_FOLDER"], file_name))
#     return render_template("experiment/configure_dataset.html", file_name=file_name, tables=df.to_html())

app/home/__init__.py
from flask import Blueprint # Import flask Blueprint class for the blueprint object

bp = Blueprint("home", __name__) # Create a blueprint object for the home blueprint, with the name "home"

from app.home import routes # Import the routes module from the home package

app/home/routes.py
from flask import render_template, redirect, url_for
from app.home import bp
from app.extensions import db
from app.models import result

@bp.route("/") # Decorator for the index function, which is the view function for the index page
def index(): # View function for the index page
    db.create_all()
    return render_template("home/home.html") # Render the home template (home.html), which will fill any jinja2 template tags with the values provided in the render_template function call

app/results/__init__.py
from flask import Blueprint # Import flask Blueprint class for the blueprint object

bp = Blueprint("results", __name__) # Create a blueprint object for the results blueprint, with the name "results"

from app.results import routes # Import the routes module from the results package

app/results/routes.py
from flask import render_template, redirect, url_for, flash, request, jsonify, current_app
from app.results import bp
import os
from app.results import report
from app.models.result import Result
from app.extensions import db

@bp.route("/<filename>") # Decorator for the index function, which is the view function for the index page
def index(filename): # View function for the index page
    # find all png files in the static folder with the filename
    files = []
    #print current working directory
    print(os.getcwd())
    for file in os.listdir(os.path.join(current_app.config['CHARTS_FOLDER'])):
        # if the filename is in the file name, and it is a png file
        if filename in file and file.endswith('.png'):
            files.append(file)

    run_png = None
    box_png = None
    time_png = None
    for file in files:
        if 'run' in file:
            run_png = file
        elif 'box' in file:
            box_png = file
        elif 'time' in file:
            time_png = file
    
    for file in files:
        print(file)

    # Add the results to the database
    return render_template("results/results.html")
    # return render_template("results/results.html", run_png = run_png, box_png = box_png, time_png = time_png) # Render the results template, which will fill any jinja2 template tags with the values provided in the render_template function call

@bp.route("/history")
def history():
    results = Result.query.all()
    return render_template("results/history.html", results=results)

# @bp.route("/history/<filename>")
# def history_file(filename):
#     return render_template("results/history_file.html", filename=filename)

app/templates/acknowledgements/acknowledgements.html
{% extends "default.html" %}
{% block title %}Acknowledgements | {{ super() }}{% endblock%}
{% block body %}
<h1>Acknowledgements</h1>
<div class="row">
    <div class="col">
        <p>
            GRASP-HPO and GRASP-WEB were developed by:
        <ul>
            <li>Shinwoo Kim<sup>1</sup></li>
            <li>Enoch Li<sup>1</sup></li>
            <li>Jack Bellamy<sup>1</sup></li>
            <li>Zi Han Ding<sup>1</sup></li>
            <li>Zane Kissel<sup>1</sup></li>
            <li>Gabriel Otsuka<sup>2</sup></li>
        </ul>
        and overseen by:
        <ul>
            <li>Dr. Daniel Mossé<sup>1</sup> and</li>
            <li>Dr. Silvio E. Quincozes<sup>2</sup></li>
        </ul>

        This project is a collaboration between the University of Pittsburgh and the Federal University of Pampa.<br />

        </p>
        <sup>1 : University of Pittsburgh</sup><br />
        <sup>2 : Federal University of Pampa</sup>

    </div>
    <div class="col border-left">
        <p>
            The GRASP-HPO project is proud to use and support the following software projects.
        <ul>
            <li><a href="https://www.ray.io/">Ray</a> - Python library for easy machine learning applications.</li>
            <li><a href="https://www.python.org/">Python</a> - A robust scripting language.</li>
            <li><a href="https://flask.palletsprojects.com/en/3.0.x/">Flask</a> - A framework written in Python that
                powers this apps</li>
            <li>and so much more.</li>
        </ul>
        </p>
        <p>
            GRASP-HPO is based upon the ideas developed from <a
                href="https://ieeexplore.ieee.org/document/9452077">previous work</a><sup>A</sup> by <em>S. E.
                Quincozes, et
                al.</em> which used a GRASP-based technique for feature selection in IDSs built using machine learning.
        </p>

        <p>
            We would also like to thank the Office of University Communications and Marketing at the University of
            Pittsburgh for providing much of the CSS that is used in this app.
        </p>
        <sup>A: S. E. Quincozes, D. Mossé, D. Passos, C. Albuquerque, L. S. Ochi and V. F. dos Santos, "On the
            Performance of GRASP-Based Feature Selection for CPS Intrusion Detection," in IEEE Transactions on Network
            and Service Management, vol. 19, no. 1, pp. 614-626, March 2022, doi: 10.1109/TNSM.2021.3088763</sup>
    </div>
</div>
<hr />

<script src="{{ url_for('static', filename='js/form-wizzard.js') }}" type="text/javascript"></script>
{% endblock %}

<!-- Form Wizzard Adopted From: https://www.w3schools.com/howto/howto_js_form_steps.asp -->

app/templates/default.html
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"
    type="text/css" />
  <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" type="text/css" />
  <link rel="stylesheet" href="{{ url_for('static', filename='css/custom.css') }}" type="text/css" />

  <title>{% block title %} GRASP-HPO {% endblock %}</title>
</head>

<body>
  <div id="pittbar" class="header" role="banner">
    <div class="container">
      <div class="row">
        <div class="col">
          <div class="site-identity">
            <a href="/">
              <span>GRASP-HPO</span>
              Hyperparameter Optimization Using GRASP-Based Techniques
            </a>
          </div>
        </div>
      </div>
    </div>
    <nav class="container navbar navbar-expand-lg navbar-dark">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
        aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-item nav-link" href="{{url_for('home.index')}}">Home</a>
          <a class="nav-item nav-link" href="{{url_for('experiment.index')}}">New Experiment</a>
          <a class="nav-item nav-link" href="{{url_for('results.index', filename="test")}}">Results</a>
          <a class="nav-item nav-link" href="https://github.com/shinwookim/GRASP-HPO">Source Code</a>
          <a class="nav-item nav-link" href="{{url_for('acknowledgements.index')}}">Acknowledgements</a>
        </div>
      </div>
    </nav>
  </div>

  <div class="main-container container">
    <div class="row">
      <div class="col">{% block body %} {% endblock %}</div>
    </div>
  </div>

  <footer>
    <div class="footer">
      <div class="container">
        <div class="row">
          <div class="col">
            <div class="site_title">
              <div class="pitt-shield">
                <img src="{{ url_for('static', filename='img/pitt_shield_white.png') }}" class="h-100"
                  alt="University of Pittsburgh shield" />
                <img src="{{ url_for('static', filename='img/pampa_logo_negative.png') }}"
                  alt="Universidade Federal do Pampa Logo" />
              </div>
              <div class="site-identity">
                <a href="/">
                  GRASP-HPO: Hyperparameter Optimization Using GRASP-Based Techniques
                </a>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col">
            <div class="sections">
              <!-- <section>
                <div class="contact-info">
                  <p>
                    University of Pittsburgh<br />
                    Department of Computer Science<br />
                    Sennott Square Building<br />
                    210 S. Bouquet Street<br />
                    Pittsburgh, PA 15260<br />
                  </p>
                </div>
              </section> -->
              <!-- <section>
                                <h3>Resources</h3>
                                <ul class="two-column">
                                    <li><a href="/">Quae ab illo inventore</a></li>
                                    <li><a href="/">Veritatis et quasi</a></li>
                                    <li><a href="/">Architecto beatae</a></li>
                                    <li><a href="/">Vitae dicta sunt</a></li>
                                    <li><a href="/">Explicabo enim</a></li>
                                    <li><a href="/">Ipsam voluptatem</a></li>
                                    <li><a href="/">Aut odit aut fugit</a></li>
                                    <li><a href="/">Sed quia&nbsp;consequuntur</a></li>
                                    <li><a href="/">Magni dolores&nbsp;eos qui</a></li>
                                    <li><a href="/">Ratione voluptatem</a></li>
                                    <li><a href="/">Sequi nesciunt</a></li>
                                </ul>
                            </section> -->
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col">
            <div id="copyright">
              <span>Copyright 2023</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </footer>
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"
    type="text/javascript"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"
    type="text/javascript"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"
    type="text/javascript"></script>
</body>

</html>

app/templates/experiment/configure_dataset.html
{% extends "default.html" %}
{% block title %}Home | {{ super() }}{% endblock%}
{% block body %}
<h1>New Experiment</h1>
<div class="jumbotron">
    <code>{{file_name}}</code>
    <div>
        {{tables | safe}}
    </div>
</div>
<!-- <script src="{{ url_for('static', filename='js/form-wizzard.js') }}" type="text/javascript"></script> -->
{% endblock %}

app/templates/experiment/experiment.html
{% extends "default.html" %}
{% block title %}Home | {{ super() }}{% endblock%}
{% block body %}
<h1>New Experiment</h1>
<div class="jumbotron">
    <form id="regForm" action="" method="POST">
        <!-- One "tab" for each step in the form: -->
        <div class="tab form-group">
            <label for="formFileLg" class="form-label">Upload Dataset</label>
            <input class="form-control form-control-lg" id="formFileLg" type="file">
        </div>

        <div class="tab">
            <label for="exampleFormControlTextarea1">Configure Dataset</label>
            <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
        </div>


        <div class="tab">Select HPO Algorithms
            <div class="form-check">
                <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
                <label class="form-check-label" for="defaultCheck1">
                    GRASP-HPO
                </label>
            </div>
            <div class="form-check">
                <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
                <label class="form-check-label" for="defaultCheck2">
                    GRASP-HPO
                </label>
            </div>
            <div class="form-check">
                <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
                <label class="form-check-label" for="defaultCheck2">
                    GRASP-HPO
                </label>
            </div>
            <div class="form-check">
                <input class="form-check-input" type="checkbox" value="" id="defaultCheck3">
                <label class="form-check-label" for="defaultCheck3">
                    GRASP-HPO
                </label>
            </div>
            <div class="form-check">
                <input class="form-check-input" type="checkbox" value="" id="defaultCheck4">
                <label class="form-check-label" for="defaultCheck4">
                    GRASP-HPO
                </label>
            </div>
            <div class="form-check">
                <input class="form-check-input" type="checkbox" value="" id="defaultCheck5">
                <label class="form-check-label" for="defaultCheck5">
                    GRASP-HPO
                </label>
            </div>
            <div class="form-check">
                <input class="form-check-input" type="checkbox" value="" id="defaultCheck6">
                <label class="form-check-label" for="defaultCheck6">
                    GRASP-HPO
                </label>
            </div>
        </div>

        <div style="overflow:auto;">
            <div style="float:right;">
                <button type="button" id="prevBtn" onclick="nextPrev(-1)">Previous</button>
                <button type="button" id="nextBtn" onclick="nextPrev(1)">Next</button>
            </div>
        </div>

        <!-- Circles which indicates the steps of the form: -->
        <div style="text-align:center;margin-top:40px;">
            <span class="step"></span>
            <span class="step"></span>
            <span class="step"></span>
        </div>

    </form>
</div>
<script src="{{ url_for('static', filename='js/form-wizzard.js') }}" type="text/javascript"></script>
{% endblock %}

<!-- Form Wizzard Adopted From: https://www.w3schools.com/howto/howto_js_form_steps.asp -->

app/templates/experiment/new_experiment.html
{% extends "default.html" %}
{% block title %}Home | {{ super() }}{% endblock%}
{% block body %}
<h1>New Experiment</h1>
<div class="jumbotron">
    <form method="POST" enctype="multipart/form-data">
        <label for="project_name">Project Name:</label>
        <input type="text" id="project_name" name="project_name"><br><br>
        <label for="project_description">Project Description:</label>
        <input type="text" id="project_description" name="project_description"><br><br>
        <button type="submit" class="btn btn-primary">Create Experiment</button>
    </form>
</div>
<script src="{{ url_for('static', filename='js/form-wizzard.js') }}" type="text/javascript"></script>
{% endblock %}

<!-- Form Wizzard Adopted From: https://www.w3schools.com/howto/howto_js_form_steps.asp -->

app/templates/experiment/upload_dataset.html
{% extends "default.html" %}
{% block title %}Home | {{ super() }}{% endblock%}
{% block body %}
<h1>New Experiment</h1>
<div class="jumbotron">
    <form method="POST" enctype="multipart/form-data">
        <label for="dataset">
            <h2>Upload Dataset</h2>
        </label>
        <input type="file" id="dataset" name="dataset" />
        <button type="submit" class="btn btn-primary">Upload</button>
    </form>
</div>
<script src="{{ url_for('static', filename='js/form-wizzard.js') }}" type="text/javascript"></script>
{% endblock %}

app/templates/home/home.html
{% extends "default.html" %} {% block title %}Home | {{ super() }}{% endblock%}
{% block body %}
<div class="jumbotron">
  <h1 class="display-4">GRASP-HPO</h1>
  <p>
    Identifying the right set of hyperparameters to use is critical in training any machine learning model. However,
    optimally searching for the best set of hyperparameters is a computationally expensive task. Here, we introduce a
    novel method of tuning hyperparameters, <strong>GRASP-HPO</strong>, which applies the principle of
    Greedy Randomized Adaptive Search Procedure metaheuristic and evaluate its effectiveness on various datasets
    compared to other popular hyperparameter optimization algorithms.
  </p>
  <p>
    GRASP-HPO operates in two key phases: a greedy randomized phase and a local search phase. The first greedy
    randomized phase identifies simple and potentially promising solutions. In this phase we randomly select a subset of
    hyperparameters. Then, the second local search phase subsequently optimizes these candidate solutions. It tests
    various combinations of values within a defined threshold for these hyperparameters.
  </p>
  <p>
    By iterating through these two steps, we can use each iteration to focus on different hyperparameters and value
    combinations. Ultimately, we can identify the best set of hyperparameters to use for a given dataset in this way.
  </p>
  <p>
    Furthermore, we look at a particular application of GRASP-HPO in the context of training a machine learning model
    that can be used to detect threats in electrical substations using the <a
      href="https://www.kaggle.com/datasets/sequincozes/ereno-iec61850-ids">
      ERENO IEC-61850 Intrusion Dataset</a>.
  </p>

  <a href="{{ url_for('experiment.index') }}" type="button" class="btn btn-primary btn-lg">
    Create New Experiment
  </a>
</div>

{% endblock %}

app/templates/results/history.html
{% extends "default.html" %}
{% block title %}Results | {{ super() }}{% endblock%}
{% block body %}
<h1>Experiment History</h1>
<div class = "col text-center">
    <table >
        <tr>
            <th>Experiment ID</th>
            <th>Input Filename</th>
            <th>Result Filename</th>
            <th>Result HTML</th>
            <th>Timestamp</th>
        </tr>
        {% for result in results %}
        <tr>
            <td>{{ result.id }}</td>
            <td>{{ result.input_filename }}</td>
            <td>{{ result.result_filename }}</td>
            <td>{{ result.result_html }}</td>
            <td>{{ result.timestamp }}</td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

app/templates/results/results-bkup.html
{% extends "default.html" %}
{% block title %}Results | {{ super() }}{% endblock%}
{% block body %}
<h1>Experiment Results</h1>
<div class="row">

    <div class="col text-center">
        <img src="https://sites.pitt.edu/~shk148/assets/img/projects/PPG-ML1.png" class="w-100" />
    </div>
    <div class="col text-center">
        <strong>Summary</strong>
        <p class="text-left">
            The influence of the categorical variable on the regression model is minimal as indicated on the variable
            importance plot. Hence, using different combinations of these variables do not seem to yield any visible
            changes. On the other hand, for the classifier, the results of fixing the two categorical variables are
            huge. By using the hardest prediction combination, most of the classifier’s predictions are non-events.
            However, if we use the worst-case combinations, most of the predictions are events which seems to signify a
            high number of false positives. Indeed, in every case besides 100≤𝙶≤150 we seem to get high proportions of
            events. Hence, we can clearly see that the predictive trends vary among the two combination choices (or any
            variances in the categorical variable as we saw in the above variable importance analysis). As for the
            regression’s surface plot, it suggests that the effects of the categorical variables are minimal in
            determining the predictions (which is backed by our analysis of the variable importance).</p>
    </div>
</div>
<div>
    <h2>Statistics</h2>
    <ul>
        <li>Best Alg: GRASP-HPO</li>
        <li>Best F1-Score: 0.984620060003265</li>
        <li>Best Hyperparameters:
            <code>'objective': 'binary:logistic', 'eval_metric': ['logloss', 'error'], 'max_depth': 3,
            'min_child_weight': 1, 'subsample': 0.984620060003265, 'eta': 0.0039969648279426055}
            Best model total accuracy: 0.9713</code>
        </li>
    </ul>
</div>
<button type="button" class="btn btn-primary btn-lg btn-block">Download Results</button>
{% endblock %}

app/templates/results/results.html
{% extends "default.html" %}
{% block title %}Results | {{ super() }}{% endblock%}
{% block body %}
<h1>Experiment Results</h1>
<div class="row">

    <div class="col text-center">
        <img src="{{ url_for('static', filename = 'charts/' + run_png ) }}" alt="Results" class="w-100" />
        <img src="{{ url_for('static', filename = 'charts/' + box_png ) }}" alt="Results" class="w-100" />
        <img src="{{ url_for('static', filename = 'charts/' + time_png ) }}" alt="Results" class="w-100" />
    </div>

</div>
<button type="button" class="btn btn-primary btn-lg btn-block">Download Results</button>
{% endblock %}

templates/home.html
{% extends "default.html" %} {% block title %}Home | {{ super() }}{% endblock%}
{% block body %}
<div class="jumbotron">
  <h1 class="display-4">GRASP-HPO</h1>
  <p class="lead">
    <strong>GRASP-HPO</strong> is a novel method of optimizing Hyperparameters
    in machine learning models.
  </p>

  <a
    href="{{ url_for('experiment') }}"
    type="button"
    class="btn btn-primary btn-lg"
  >
    Create New Experiment
  </a>
</div>

{% endblock %}